### ISSUE TITLE
Observers do not work with the discord adapter

### ISSUE THREAD

**Issue by bensontrinh** [yetibot/yetibot#1123]
**Describe the bug**
Adding an observer with the discord integration does not work. 

**To Reproduce**
```
!obs -e react :clown_face:  = meme Dr Sharp clown: {{body}}
```
Then react to a message with the clown emoji. 

**Expected behavior**
Yetibot should have sent a Dr Sharp clown emoji with the text of the reacted

**Comment by devth** [comment]
![image](https://github.com/user-attachments/assets/7befbe93-57d7-4243-b45f-a4eab3dc17d9)
