### ISSUE TITLE
yetibot responds to privmsg with privmsg back to sender

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#261]
The difference between channel messages and privmsg:

DEBUG [yetibot.adapters.irc] - raw :read :devth!~devth@94.231 PRIVMSG yetibotz :hi there
DEBUG [yetibot.adapters.irc] - raw :read :devth!~devth@94.231 PRIVMSG #yeti :hi fair

**Comment by devth** [comment]
This was done quite awhile ago.
