### ISSUE TITLE
terminate commands after a timeout

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#410]
With core.async at https://github.com/devth/yetibot.core/blob/observe/src/yetibot/core/handler.clj#L36

**Comment by functor-soup** [comment]
@devth  Hopefully this question makes some sense as I'm still sifting through the code, is the timeout  per command and the total timeout for a `piped` command  chain is the `(timeout/per-command) * (commands in piped chain)` ?

**Comment by functor-soup** [comment]
@devth nevermind my earlier question, the way things are right now, seems like it easier to go with a timeout that is constant for both a singular and chained function call.

**Comment by devth** [comment]
Yes it's easier to do it that way. Good question though. Thinking from a usability perspective I think you'd want a constant timeout, regardless of how many commands. Otherwise, if the timeout was e.g. 10 seconds, a command with 6 sub-commands would get a 1 minute timeout, which is quite crazy.

**Comment by devth** [comment]
Also this timeout could be configurable by the user, with a sensible default like 10 seconds, and a friendly error message if it times out. 

Another idea is a soft timeout where we'd fire a reply after 10 seconds like "This seems to be taking awhile...still working on it" and let it continue trying to fulfill the request. After a longer timeout, (60 seconds)? we give up completely and return the hard timeout error message.

**Comment by functor-soup** [comment]
@devth I have code working for the first scenario, will modify it cause the second one sounds cooler. Question: how does async and deferred operations fit in with user friendliness (action of least surprise) when it comes to a single point of interaction (chat-window)?(or does it not matter at all?)

**Comment by devth** [comment]
@functor-soup I think a soft timeout with messaging improves the UX.

Previously if a command was taking a long time to run, there was nothing, and the user is left wondering if Yetibot crashed or disconnected. This feature is meant to address that. It's taking an edge case with a (currently) bad experience and improving it for the user. 

I'm not sure there are formal guidelines on UX for chatbots but intuitively this feels like an improvement. However, once we actually try it out we may find that we want to change it, as often happens.
