### ISSUE TITLE
history should take more params to specify which types of history

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#426]
1. With no options `history` outputs all non-command non-yetibot history
1. `--include-commands` (commands are excluded by default)
1. `--commands-only`
1. `--include-yetibot` (yetibot is excluded by default)
1. `--yetibot-only` (overrides 2)
1. Maybe add --since --until so we can slice history by time?
1. Pagination? Currently history just returns 30 results.

**Comment by cvic** [comment]
Param for `history`?

**Comment by devth** [comment]
Yep, probably. At least the data exists now.

`uptime` lol

**Comment by devth** [comment]
`meme insanity: cvic agrees to fix all issues by tomorrow`

**Comment by devth** [comment]
Closing in favor of #875 which consolidates a bunch of history improvements.
