### ISSUE TITLE
my 'command'

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#427]
Investigate generic ways of mapping user-to-args for any commands.

`!my temp`
look up mapping if exists: `{:temp {"devth" "98104"}}`
turns into:
`!temp 98104`

other areas:
- jira issue lookup
- github user-specific lookups
- aliases: this could enable all sorts of things!

**Update**: my should just be user-specific variables.

!my loc = 98104

stores a mapping: {"devth" {:loc 98144}} in config

These mappings can make use of by other commands and alises.

```
!weather (default is to lookup weather for the user who requested it). If the
user doesn't have `my weather` var set, it prompts them to set it.
!jira (lookup my top 5 issues)
```

**Comment by devth** [comment]
from @jcorrado:
> @devth - how challenging would it be to surface the user's TZ in context passed to commands (the map with `match`, etc.) like we do for yetibot itself

I think `my` could have a default key of timezone, similar to how `channel` has a default setting of `broadcast: false`. 

- When the adapter provides the TZ (Slack) we can set its default value. 
- When the adapter does not provide the TZ (IRC) the user can set it themselves, similar to `channel set <K> <V>`

Then we can propagate TZ as part of the user settings which would be a submap of the `user` entity in the cmd args. It has the potential to be nil, in which case commands that depend on it should error out and tell the user to set their TZ with `user set tz <tz>` or `my tz <tz>` whatever the command ends up being.
