### ISSUE TITLE
could xargs take a subexpression to run each command through a multistep pipeline?

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#432]

**Comment by cvic** [comment]
An example?

**Comment by devth** [comment]
Maybe neat idea but fairly complex, especially for a user. Closing unless it comes up again.

Arbitrary (bad) example would be something like:

```
!list 1 2 3 | xargs "complete %s | random"
```

That's ugly though and we can already do the equivalent:

```
!list 1 2 3 | xargs complete | xargs random
```
