### ISSUE TITLE
whalesay command

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#537]

**Comment by devth** [comment]
Via docker:
```
docker run docker/whalesay cowsay boo
```

Example of [running docker from Yetibot](https://github.com/devth/yetibot-codeclimate/blob/46a59493ff7d249dcc9d33b479f41be623ec65a8/src/yetibot_codeclimate/analyze.clj#L131)

**Comment by cvic** [comment]
Combine it with a source of quotes for a killer command :D 

Inspiration here:
https://github.com/aaronsaderholm/whalesay-vatican
