### ISSUE TITLE
When a command isn't configured, don't completely disable it

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#559]
Instead, set its evaluation to return a message about how to configure it

**Comment by devth** [comment]
Would also be useful to have a command that lists non-configured commands.

**Comment by jkieberk** [comment]
Would it be more idiomatic to have all of the config information in one file? (maybe in yetibot.core?)  and then just pass the command name to a function in that file that would return how to configure that command?  

Versus having individual functions in all the command files that need to be configured?

New to clojure (and <1 year of software engineering in general) so not sure what the best way to handle this is... Having the config requirements in one place might be good? But at the same time I could see it also being a good idea to keep the config in the same place as the file that is using it...

**Comment by devth** [comment]
@jkieberk yeah, I definitely want to avoid stuff like `when model/configured?` and maybe even avoid having to explicitly fetch config from various places.

I'm thinking about working something into `cmd-hook` where the users of `cmd-hook` might pass in a config path and a clojure-spec that the expected config should conform to. If it doesn't exist or doesn't conform, then the command would still get hooked but output of that command would just be a friendly error message that maybe links to docs on how to configure the command.

I need to put a little more thought into this, but that's the gist of what I'm imaging as of now. This idea would depend on migrating to clojure-spec from schema, and I'm sorta waiting for Clojure 1.9 to be released before I do it.

**Comment by jkieberk** [comment]
Sounds good!

**Comment by devth** [comment]
This issue was moved to yetibot/yetibot.github.io#22
