### ISSUE TITLE
Add support for Hipchat adapter

### ISSUE THREAD

**Issue by thenonameguy** [yetibot/yetibot#560]

**Comment by devth** [comment]
Hi @thenonameguy. Is this something you'd be interested in contributing (no worries if not)? Does your team use Hipchat and you're wanting to use Yetibot with it? Thanks.

**Comment by thenonameguy** [comment]
Hey, yeah I would like to, just wanted to create an issue first as described in the README. Where does the adapter code live? I would also gladly try to modularize it, if possible.

**Comment by thenonameguy** [comment]
Found it, nvm, I'll see what I can do next week.

**Comment by devth** [comment]
Awesome! Let me know if you have questions along the way.

**Comment by devth** [comment]
@thenonameguy let me know if you have questions or want a PR along the way :)

**Comment by thenonameguy** [comment]
Hey, it turned out to be a bit more complicated then I expected (Hipchat's API is not the best thing to interface with). I stand defeated :(

**Comment by devth** [comment]
@thenonameguy did you check out https://github.com/owainlewis/hipchat ? I'd be willing to take an initial stab at it.

**Comment by cvic** [comment]
Well :D 
https://www.atlassian.com/partnerships/slack

**Comment by devth** [comment]
Closing 😂
