### ISSUE TITLE
Switch from Schema to clojure.spec

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#576]
- spec the minimum attributes and their types for a user model e.g. `{:id "~yetibot" :username "yetibot"}`
- use spec for config shapes
- spec the `irc` object in Slack so we know what data are available
- adapters
- warn loudly in logs when a namespace tries to load its config but it's invalid

**Comment by cvic** [comment]
Does
```(defn non-blank-string? [x] (and (string? x) (not (string/blank? x))))```

look like a good replacement for 
https://github.com/yetibot/yetibot.core/blob/master/src/yetibot/core/schema.clj#L5 ?

**Comment by devth** [comment]
Sure. Where's that? Or is that new code you're proposing we introduce?

**Comment by cvic** [comment]
New code. I have to test it first.

**Comment by cvic** [comment]
I'll start with 
https://github.com/yetibot/yetibot.core/blob/master/src/yetibot/core/util/config.clj#L56

and use this for inspiration 
https://gist.github.com/ghoseb/9f81ca592a56c23a4f7564e813d23ea5#file-clj_spec_playground-clj-L75

**Comment by devth** [comment]
- https://github.com/yetibot/yetibot/pull/959
- https://github.com/yetibot/yetibot.core/pull/106
