### ISSUE TITLE
Automatically append _ or some char if name is taken in irc

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#598]

**Comment by tmayse** [comment]
Would it make sense to replicate the functionality [here](https://github.com/colloquy/colloquy/blob/d777556f6824155a20db5663be824a65402e1600/Chat%20Core/MVIRCChatConnection.m#L1940-L2015)? 

It's significantly more robust than the existing adapter. Is any of that "too much" for Yetibot?

Is anyone else working on this functionality?

**Comment by devth** [comment]
Yes, that's the functionality I had in mind.

I don't think it's too complex for Yetibot. The equivalent in Clojure should be much shorter / easier to read.

Pretty sure no one is working on this.

Let me know if you have more questions! I'm usually available on [Yetibot Slack](https://slack.yetibot.com). There's a #dev channel for dev discussions.

**Comment by seangates** [comment]
Dupe of #457?

**Comment by devth** [comment]
Yep good catch. Thanks @seangates!
