### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by martinodb** [yetibot/yetibot#627]
Hello!

I'm trying to get started with Yetibot, following the installation instructions. I'm not using Docker, instead I downloaded the latest zip and did a "lein run", as described in the instructions. I get the following error:

```
ERROR [yetibot.core.init:32] - Yetibot failed to start: please ensure config is in place at yetibot.core.config_mutable$config_path@140eec0  and that it is well-formed (see the log above for details)
```
Is there a simple "getting started" tutorial, for trying Yetibot locally in a REPL?

**Comment by devth** [comment]
Hi @martinodb, thanks for reporting this issue!

Most of the recent docs are around using Docker. I will absolutely improve the docs with instructions on how to `lein run`. Aiming to get to this in the next day or two.

**Comment by devth** [comment]
Made a quick fix to prevent the error above. You should be able to `lein run` and not worry about mutable config (yetibot.core will create it for you in `config/mutable.edn` if it doesn't exist. You do however need to provide the immutable config.

Docs on that are at [CONFIGURATION](https://github.com/devth/yetibot.core/blob/master/doc/CONFIGURATION.md). In particular, see config samples linked from that doc. If anything doesn't make sense or you have suggestions for improving those docs let me know!

I'll still plan on working on a simpler Getting Started guide.

**Comment by martinodb** [comment]
Thanks for the quick reply! :)

OK, so I downloaded the yetibot zip again, did "lein run" and this time it started and loaded a default mutable config, but then gave an error message when it had to load the immutable config. So I downloaded "config.sample.edn", placed it (unmodified) in the config directory, and did "lein run" again. As expected, since it's just an example, yetibot got to the same point as before and then printed this error message:

```
INFO [yetibot.core.db:28] - ☑ Datomic connected
INFO [yetibot.core.adapters.init:33] - Trying Register adapters
WARN [yetibot.core.adapters.init:36] - Error on Register adapters clojure.lang.ExceptionInfo: Invalid adapters config
 at clojure.core$ex_info.invokeStatic (core.clj:4617)
```

Then there are a few more INFO messages and then it apparently gets stuck. The last message is:

`INFO [yetibot.core.loader:41] - ☑ Loaded 82 namespaces matching [#"^yetibot\.(core\.)?commands.*" #"^.*plugins\.commands.*"]`

So, I guess my first question is, do I need to configure those adapters properly before I can use Yetibot at all, or can I leave that for later and try it out with a REPL or similar? I don't have a Slack account, and I'm guessing it makes sense to try things locally before connecting to freenode and whatnot.

Regarding Docker, no doubt, the documentation makes it clear that that's the preferred option. I just can't use it right now because it requires 64-bit Ubuntu I'm still running 32-bit, which I shouldn't, but anyway since the "lein run" option was mentioned, I figured I could give it a shot.

PS: sorry about the total n00b-ness. Hopefully it gives you ideas for your tutorial ;)

**Comment by devth** [comment]
This is great feedback. Thanks!

No I don't currently have it setup for use without a chat adapter, but that is a great idea. I want to make it as easy as possible to demo, so some kind of repl-mode when there's no config makes sense. I'll think about adding this.

**Comment by martinodb** [comment]
Hey, I found this little tool in your repos, so maybe you already had a similar idea 4 years ago. I don't know how relevant or useful it may be, but here it is:

[yetibot-cli](https://github.com/devth/yetibot-cli)

**Comment by devth** [comment]
`yetibot-cli` is/was an API client to talk to a Yetibot over HTTP, so it wouldn't help in this case :)

**Comment by devth** [comment]
Hey @martinodb, quick update:

I added some initial docs at:
https://github.com/devth/yetibot/blob/master/doc/GETTING_STARTED.md

However, I found a bug in the IRC adapter and am working on that currently, tracked by #633. Once that's fixed I'll tackle #628 and update the Getting Started docs with simplified instructions. Leaving this open until all that's done!

**Comment by martinodb** [comment]
Awesome, I'll stay tuned ;)

**Comment by jkieberk** [comment]
Hey! I'm new to the project too.

I went to try and run it and got the same error: `Error on Register adapters clojure.lang.ExceptionInfo: Invalid adapters config`

I got the error both when I pasted this:
`{:yetibot
  :adapters {:freenode {:type "irc",
                        :username "my-yetibot",
                        :host "chat.freenode.net",
                        :port "7070",
                        :ssl "true"}}}}
`
And also [this](https://github.com/devth/yetibot.core/blob/master/config/config.sample.edn) file 
into my `mutable.edn` file. (I added in the extra } as seen in my above commit to the first config).

Hope this helps! :)

Also, is there an official slack or irc channel where people hang out in?

**Comment by devth** [comment]
Hi @jkieberk, I have a Slack for Yetibot but I didn't setup a public inviter yet. Working on it now, tracked by https://github.com/devth/yetibot/issues/639.

**Comment by devth** [comment]
Improved [Getting Started docs](https://github.com/devth/yetibot/blob/master/doc/GETTING_STARTED.md#run-it) with a script example.

**Comment by devth** [comment]
This issue was moved to yetibot/yetibot.github.io#21
