### ISSUE TITLE
Switch yetibot's badges in the README to flat-squared style

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#634]

**Comment by cvic** [comment]
like these https://forthebadge.com ?

**Comment by devth** [comment]
Yeah. Not sure if we should use `for-the-badge` style or `flat-square`:
http://shields.io/#styles

FTB is kinda big but they look nice. Would be cool to see it.

**Comment by devth** [comment]
This issue was moved to yetibot/yetibot.github.io#20
