### ISSUE TITLE
Figure out how to get actual latest to reflect in crossclj docs

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#640]
It's using the bad 1.0.x release :sob:
https://crossclj.info/doc/yetibot/latest/index.html

**Comment by cvic** [comment]
So... 
https://crossclj.info/faq.html

*) Source code is included into project's artifact, and hosted publicly on GitHub (i.e. there is a github reference on the project's POM under the url or scm/connection fields). This almost ensures that the source code license is compatible with CrossClj's usage.

to be solved?

**Comment by devth** [comment]
The problem is at one point I released a 1.0 RC and now CrossClj thinks that's the "latest". It will probably be that way until Yetibot hits 1.0+.

**Comment by cvic** [comment]
> yetibot index 1.0.0-RC7 docs

:-D

**Comment by devth** [comment]
This issue was moved to yetibot/yetibot.github.io#19
