### ISSUE TITLE
Build a static docs site for yetibot.com with https://perun.io/

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#672]
Write guides on useful topics:

- Poking at a Yetibot with `eval`. Debugging. Listing users, rooms.

**Comment by cvic** [comment]
Well, check it out 
https://github.com/cvic/yetibot.github.io/tree/perun-site

**Comment by cvic** [comment]
Good for inspiration 
*) just Clojure things :-D
https://crossclj.info/doc/yetibot/latest/index.html 
*) Great design, easy to read, and very thorough with introductory and advanced topics.
http://riemann.io/
*) A Sass documentation generator that utilizes inline comments to make pretty and powerful docs. 
http://sassdoc.com/

via
https://github.com/PharkMillups/beautiful-docs

**Comment by include** [comment]
it looks great!

**Comment by devth** [comment]
Need to get this thing up! @cvic you still interested?

**Comment by devth** [comment]
Initial site is up! We'll continue to improve it but closing this for now.

https://yetibot.com

Source: https://github.com/yetibot/yetibot.github.io
