### ISSUE TITLE
Fix Midje tests

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#678]
1. is there a way to run midje tests via `lein test`?
1. need to figure out how to run tests from vim-fireplace
1. or just consider switching back to clojure.test if Midje is too much of a burden

@dawsonfi any thoughts? Looks like a bunch of [failures in tests](https://travis-ci.org/yetibot/yetibot/builds/270068841) but I haven't looked into the cause, and the problem is they aren't failing the build like I'd expect.

**Comment by dawsonfi** [comment]
Hi @devth,

About the `lein test`, it's possible by using an alias. I'm gonna open a pull request with this configuration.

I'm gonna check the failing tests and post here what i can find. :)

**Comment by dawsonfi** [comment]
Just created the PR #679 to create the `lein test` alias.

I believe that the failing tests are related to the issue #665.
Do you have any ideias on how to replace the scala api @devth?

**Comment by devth** [comment]
@dawsonfi thanks, merged.

I think I'll disable Scala API for now until we can find a replacement.
