### ISSUE TITLE
Command to watch for releases of given GitHub repos

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#729]

**Comment by kaffein** [comment]
Hey guys,

just to make sure I understand this one clearly : when talking about _watch_-ing for releases, are we talking about having a command for _only_ listing releases of github repos, which would then (I guess) comes down to using tentacles `repo api` to fetch the info using :

`(tentacles.repos/releases "irresponsible" "tentacles")`

or do we intend to have some kind of github notifications on new releases, such as what we have when someone pushes to a repo (I have seen some WIP in the codebase like the following) :

```
(defn notify-add-cmd
  "gh notify add <org>/<repo-name> # sets up notifications to this channel on pushes to <repo-name>"
  [{[_ repo] :match chat-source :chat-source}]
  "Not yet implemented")
```
in the latter case, it seems that people monitors an rss feed embedded in the github release page.

thanks ;-)

**Comment by devth** [comment]
Hey @kaffein, I don't think the desired behavior is defined. A true subscription would be cool, but adds some technical overhead, like exposing a public webhook endpoint for Yetibot. This might not be ideal since many YB instances are likely run internally.

Maybe we start with the ability to look up releases then go from there? e.g. we could use the existing `cron` to query on a regular interval.
