### ISSUE TITLE
Migrate away from Weather Underground

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#740]
As @jcorrado mentioned in https://github.com/yetibot/yetibot/issues/594 [WU is ending free service](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api).

Possible alternative is [OpenWeatherMap](https://openweathermap.org/price). Free tier is still pretty generous.

**Comment by jcorrado** [comment]
I'm happy to have a go at this one.

**Comment by devth** [comment]
Awesome!

**Comment by jcorrado** [comment]
I have a basic version of this running on my box now, using Weatherbit.io.  Tomorrow(ish) I will write up some thoughts and observations on the three APIs I reviewed: [OpenWeatherMap](https://openweathermap.org/api), [Weatherbit.io](https://www.weatherbit.io/api), and [The National Weather Service](https://www.weather.gov/documentation/services-web-api).  There are some trade offs to be made with each, and different ways we can handle city searches.

I could also use a little guidance on best practices for development, as Yetibot is a fair bit more complicated than other projects I've worked on (just what I was looking for!) :)

**Comment by devth** [comment]
Cool! Weatherbit.io looks good but looking forward to hearing your thoughts on the others.

I've been thinking about writing up a dev guide. What things do you need guidance on? Clojure workflow in general (e.g. using the repl, configuring your editor to dev interactively)? Testing model/api code? Regexesin commands? I'd be happy to answer any questions and improve dev UX based based on your feedback. Have also been thinking of posting some screencasts of working on yb.

**Comment by jcorrado** [comment]
The first part of write up is in my branch: `740-new-weather-api`'s [/doc/WEATHER_API_CONSIDERATIONS](https://github.com/jcorrado/yetibot/blob/740-new-weather-api/doc/WEATHER_API_CONSIDERATIONS.md).

I'll finish this up shortly.  And definitely will share thoughts on the dev guide bits!

**Comment by jcorrado** [comment]
Doc is ready for review, @devth and discussion on next steps.

**Comment by jcorrado** [comment]
Regarding dev tooling help, two things comes to mind:
1. If I launch `lein repl`, and then run `(start)` only a small set of modules is loaded - how can I load them all?
2. I use CIDER - would it be possible to connect to a running YB, launched either via `lein run` or by running a built uberjar directly, as I would via the CLI (either locally, or in a Docker container, for example)?

Those are the biggies for me.  More generally, some notes on your work flow would probably cover things - I just need an efficient way to be able to evaluate forms in a  repl for a running YB.

**Comment by devth** [comment]
the `WEATHER_API_CONSIDERATIONS` doc looks great! I'm going to review in more detail later today.

I pushed an update to DEV.md in https://github.com/yetibot/yetibot/commit/61e05a694a6332b94fb17ace01ff1035ec420e4a.

I think the most important part of my workflow is reloading code into the REPL as I work on it. This avoids the need to load all the available commands (though you can certainly load them all if you want). Added a note on that in DEV.md.

Regarding your second point, I used to run a standalone `nrepl` server inside Yetibot to be able to connect a REPL to a remote instance. It's currently commented out [here](https://github.com/yetibot/yetibot.core/blob/master/src/yetibot/core/webapp/handler.clj#L28) but I'll re-enable it (tracked this in https://github.com/yetibot/yetibot/issues/744).

Lastly I got a request to improve unit testing capability for commands in https://github.com/yetibot/yetibot/issues/702#issuecomment-428305844. I thought this was a good idea so I'm currently working on a `command-execution-info` function that would take a command string input and return info about:

1. which command and sub-command it matched
1. the `match` arg containing regex groups to help test regex correctness
1. optionally the result of the command
1. the parsed command AST
1. other useful stuff I can think of

**Comment by devth** [comment]
I read the `WEATHER_API_CONSIDERATIONS` doc in full. Excellent write up! 💯 Especially `curl` + `jq` examples and responses - those were super helpful. 

Glad you dove into location qualification. That's one thing the current weather command doesn't handle well (even though it's decent at suggesting locations), so Im' looking forward to that improvement when we switch to Weatherbit.io.

I'd say we ship an initial simple migration then optionally tackle bundling the cities meta data and building our own city suggestion feature.

**Comment by jcorrado** [comment]
Excellent!  I'll put together a simple first pass that works with postal codes and exact name matches.  That should be pretty quick... probably delivered next week.  After that I'd really like to work out the meta-data based local suggestions feature.  I see you're already using `clj-fuzzy` so I'll start there.
