### ISSUE TITLE
Add an option to xargs to make it use map instead of pmap so side effects are executed sequentially

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#750]

**Comment by jcorrado** [comment]
Can you provide an example of problem, please.  I'm not able to trigger a failure, but I'm not totally sure I follow the issue.

```
jereme9:57 PM
!list a0 a1 a2, b0 b1 b2, c0 c1 c2 | xargs words | xargs head 2 | xargs tail
￼￼￼￼
yetibotAPP9:57 PM
a1
b1
c1
￼
jereme9:57 PM
!list a0 a1 a2, b0 b1 b2, c0 c1 c2 | xargs words | xargs head
￼
yetibotAPP9:57 PM
a0
b0
c0
￼
jereme9:57 PM
!list a0 a1 a2, b0 b1 b2, c0 c1 c2 | xargs words | xargs tail
￼
yetibotAPP9:57 PM
a2
b2
c2
￼
jereme9:57 PM
!list a0 a1 a2, b0 b1 b2, c0 c1 c2 | xargs words | xargs head 2 | xargs tail
￼
yetibotAPP9:57 PM
a1
b1
c1
```

**Comment by devth** [comment]
In looking at this further, I realized that `pmap` returns results in order but because everything is executed in parallel the order of the side effect will be totally non deterministic. Here was the originally repro that prompted this issue:

```
!range 5 | xargs replyto @devth | nil
```

Use your own Slack username and notice how the messages arrive out of order due to the parallelism and because the command is side-effecting.

So maybe the fix for this would be to add an option to [xargs](https://github.com/yetibot/yetibot.core/blob/6b0e35d11369f17550066123fe0a03c3d5ad7907/src/yetibot/core/commands/collections.clj#L108) to make it execute results sequentially using `map` instead of `pmap` for cases like this.

**Comment by jcorrado** [comment]
I wonder if you couldn't annotate commands (similar to the `{:yb/cat #{foo bar}}` effort) to inform this type of desiction.  `xargs` could then decide on whether of not it was safe to parallelize the next batch of commands. :thinking:

**Comment by devth** [comment]
Great idea. I can’t think of another command that would repro like `replyto` anyway so it makes sense that Yetibot would know itself whether it should parallelize. There’s one other way to accomplish it: by pushing xargs down into replyto (similar to how pushing a relational operator down works in an RDBM if you’re familiar with DB internals / relational algebra).

Yet another thing to document in the dev guide!

**Comment by jcorrado** [comment]
I'm not familiar with that - can you point me towards some docs on the pattern?

**Comment by devth** [comment]
Sure, right after I write them 😂

Seriously though I’ll try to write some very soon. Good motivation!

**Comment by jcorrado** [comment]
:laughing: I more meant the RDBM operator pattern.  Or let's chat next time we overlap in #dev.

**Comment by devth** [comment]
The example in Yetibot itself is in the [`history` command](https://github.com/yetibot/yetibot.core/blob/master/src/yetibot/core/commands/history.clj#L46-L61).

Using `history | random` as an example: the history command looks ahead at the next commands in the pipeline, sees that it's a command it knows how to consume (`random`), and tells the command execution pipeline to skip it for efficiency and instead handle itself.

Imagine the default / nieve method Yetibot could potentially execute for `history | random`:

1. Load all history into a data structure
1. Pass the data structure to `random` which calls `rand-nth` on the collection to 

According to [the dashboard](https://public.yetibot.com/) we currently have 12723 entries in the history table in the database, which isn't that much but you can imagine how slow it'd be, especially as the table grows.

So instead we "push down" the `random` operation into the database [here](https://github.com/yetibot/yetibot.core/blob/f2e045002e20adccb79adbb84eb12566fc99c51e/src/yetibot/core/models/history.clj#L56-L65).

It's not even close to the sophistication of analysis that an actual DBMS uses, but if you're curious here's an article on [Pushdown Analysis](https://www.ibm.com/support/knowledgecenter/en/SS6NHC/com.ibm.data.fluidquery.doc/topics/cfptun05.html).
