### ISSUE TITLE
Karma feature to give karma points to users

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#759]
- `!karma @user <optional message>`
- `!karma leaderboard` or something
- query by time (week, month, year)
- expose it on the dashboard via graphql

**Comment by jcorrado** [comment]
I'd like to work on this.  I have an impl in my other bot project that would get this most of the way there.

**Comment by devth** [comment]
All yours! I'll try to get a fix for users bug to support this ASAP. 

- https://github.com/yetibot/yetibot/issues/555
- https://github.com/yetibot/yetibot/issues/179

**Comment by jcorrado** [comment]
With PR #781 merged in, I think this feature is in a good v1.

**Comment by devth** [comment]
Yep feels pretty good. Will get it released hopefully later today when I get a chance so we can play with it.

**Comment by jcorrado** [comment]
@devth, please close when you have a chance.  I didn't think to close in my PR.

**Comment by devth** [comment]
I'd still like to get it exposed in the GraphQL dashboard. Would be fun to see a leaderboard at https://public.yetibot.com. I think this would mean porting it from `yetibot` over to `yetibot.core` though.

**Comment by jcorrado** [comment]
I'm happy to take a swing at that - I'd enjoy to learn more about GraphQL (not sure how much will be magically handled, but at least I'd having context to begin poking at it).  I'll need a bunch of guidance on that.  But adding Karma to core seems a little odd, :thinking:

**Comment by devth** [comment]
Since everything is setup it’s pretty easy. I know it’s not exactly a core feature but almost every other db-backed model is in core too. I’m fine with it.

**Comment by jcorrado** [comment]
SGTM.

**Comment by jcorrado** [comment]
@devth, now that karma lives in core, what's involved with surfacing data via the GraphQL dashboard?

**Comment by jcorrado** [comment]
Tackling GraphQL in #858
