### ISSUE TITLE
Rename `room` command to `channel`

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#799]

**Comment by kaffein** [comment]
my dear fellows, I have two (2) questions on this issue please :

1. do we want to _only rename the command hook_ or the whole namespace and everything related to it (a little code refactoring such as var names, method names etc.) ?

2. in case we only want to _rename_ the command, even though it's not likely that someone has managed to _cron_ a command involving _room_ (which would cause the API to break I guess ^^ -- I know I'm a little paranoid here haha), do you think it's possible to maybe instead add _another command hook_ which would point to the former room methods and having the former _room command hook_ invoking the _new channel command hook_ (as a kind of _delegation_ call). It would then prevent the _breaking_ of the API ... 

the second question may not be a big deal if we really want to get rid of the room command and enforce the use of channel instead so it's just for my information ...

thanks

**Comment by kaffein** [comment]
I am going to give this one a shot if it's okay for you guys ;)

**Comment by devth** [comment]
Sounds great! Thanks!

**Comment by devth** [comment]
Thanks @kaffein 💯 👍
