### ISSUE TITLE
ask yetibot what time it is in its configured timezone

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#830]
```!time```

**Comment by sarg** [comment]
I'd like to work on this.

**Comment by devth** [comment]
Cool! We now have a `date` command (which uses `duckling`) that sorta does this already:

![image](https://user-images.githubusercontent.com/86107/66719150-07586400-eda9-11e9-904f-ed20d48b585f.png)

Would be cool if we had a dedicated time command that could take timezones so we could have Yetibot tell us what time it is in various places. Open to ideas.
