### ISSUE TITLE
Proposal: Mattermost adapter

### ISSUE THREAD

**Issue by wi1w** [yetibot/yetibot#971]
**Mattermost needed**
Mattermost is selfhosted alternative for slack. Adapter for it will be great feature.

If anyone else need it please comment on this issue with thumb up, thanx.

**Comment by leaNick** [comment]
![image](https://user-images.githubusercontent.com/13031074/67186060-e5d22a80-f3ef-11e9-8129-f6493739316c.png)

**Comment by devth** [comment]
Thanks for opening. Hoping to look at this today and maybe work on it next week!

**Comment by wi1w** [comment]
Thanks

**Comment by wi1w** [comment]
Any news?

**Comment by devth** [comment]
Not yet, got busy as usual :/ I'll try to find some time today.

**Comment by devth** [comment]
Looking at this right now. Know of any Mattermost instances I could try out for developing against? Would like to avoid setting up my own, if possible.

**Comment by devth** [comment]
Found one. I'm using https://oss.mattermost.com/opensourceway/channels/yetibot for now.

**Comment by devth** [comment]
Don't think I can create a bot account there.

**Comment by devth** [comment]
Found out they have a "Deploy to Heroku" button so I set one up: https://yetibot-mattermost.herokuapp.com/yetibot/channels/town-square

**Comment by devth** [comment]
There isn't a clj client for Mattermost, so I am attempting to generate one from the Swagger spec.

Hitting a few issues since Mattermost's swagger spec has a few bugs in it:

- https://github.com/mattermost/mattermost-api-reference/issues/468
- https://github.com/mattermost/mattermost-api-reference/issues/485

Trying to work around these by modifying the generated code to add authorization. Which is not ideal since if I have to re-gen the code I would have to re-modify the generated code. Hopefully the above 2 issues get fixed on their end.

**Comment by wi1w** [comment]
Hi.
Thanks for the work you've done.
When you can combine popular shoes and work in a single environment.
ChaiOPS cool feature in Yeti.

**Comment by devth** [comment]
Traveling for a few weeks and didn't get this finished yet. Will resume after the holidays!

**Comment by wi1w** [comment]
Have a nice days.
Thanks a lot, for yours work.

**Comment by devth** [comment]
I'm back from traveling. Working on this once again!

**Comment by devth** [comment]
Update: I have it sorta working but the websocket connection disconnects often, which is forcing me to have good reconnect handling. I was using [gniazdo](https://github.com/stalefruits/gniazdo) but that doesn't give much granular control over the socket, so I think I'm going to switch to [http.async.client](https://github.com/cch1/http.async.client) today.

**Comment by wi1w** [comment]
Good news.
Thanks a lot

**Comment by devth** [comment]
@wi1w Mattermost is supported as of `yetibot 0.5.54`! Let me know how it works for you or if you run into any issues.
