### ISSUE TITLE
Populate result/data in wolfram command

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#998]

**Comment by claytn** [comment]
@devth Would like to hear more about this. What did you have in mind for the output of the wolfram command?

**Comment by devth** [comment]
Hey @claytn!

If you're not yet familiar with data behind pipes, checkout:

- [data docs](https://yetibot.com/user-guide#data)
- [All your data are belong blog post](https://yetibot.com/blog/2019-04-22-all-your-data-are-belong)

Basically, a command can return raw data in addition to a formatted response. The user can optionally access this raw data using a couple commands like `data` or `render`. This is described in more detail in the above links.

So in the case of wolfram we return a list of images since that's a nice way to display their data, but there's also the raw text data itself.

For example, the api equivalent for:
https://www.wolframalpha.com/input/?i=distance+to+the+moon

contains stuff like:

```xml
<microsources>
<microsource>PlanetaryMoonData</microsource>
</microsources>
<datasources>
<datasource>AllensAstrophysicalQuantities</datasource>
<datasource>AstronomicalAlgorithms</datasource>
<datasource>
PlanetaryTheoriesInRectangularAndSphericalVariables
</datasource>
<datasource>SolarSystemDynamics</datasource>
</datasources>
<img src="https://www4d.wolframalpha.com/Calculate/MSP/MSP1106223f065fc2ea28a600004iggid075bib5e4c?MSPStoreType=image/gif&s=31" alt="228449 miles" title="228449 miles" width="87" height="18" type="Default" themes="1,2,3,4,5,6,7,8,9,10,11,12" colorinvertable="true"/>
<plaintext>228449 miles</plaintext>
</subpod>
```

We could build a more manageable data structure from this and return it via `:result/data`.

As a side note: I really don't like their XML API - I would first investigate if they have a more modern equivalent yet. If so, we might just be able to return the data as-is instead of restructuring.

**Comment by claytn** [comment]
@devth Ok makes sense - this would be a cool one to tackle. Once I get myself up and running I'll look into this a bit more 😃

**Comment by devth** [comment]
Cool! I'm happy to help or answer questions.
